// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8EVXO-pU8l0lG6p_3cE1IEuGZnXJdTZo',
    appId: '1:314805774101:web:fa56dd5122b615a45c6b1c',
    messagingSenderId: '314805774101',
    projectId: 'bitacoreqalpha0',
    authDomain: 'bitacoreqalpha0.firebaseapp.com',
    storageBucket: 'bitacoreqalpha0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtQq7Wy9COti0xYP8K7BzPEehasw47Qo',
    appId: '1:314805774101:android:37e744fe6dd013855c6b1c',
    messagingSenderId: '314805774101',
    projectId: 'bitacoreqalpha0',
    storageBucket: 'bitacoreqalpha0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUflj4oBy5z9IZLR2cT7N3EvQ_ueaKh0c',
    appId: '1:314805774101:ios:32d816453d6364075c6b1c',
    messagingSenderId: '314805774101',
    projectId: 'bitacoreqalpha0',
    storageBucket: 'bitacoreqalpha0.firebasestorage.app',
    iosBundleId: 'com.example.bitacoreqalpha0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUflj4oBy5z9IZLR2cT7N3EvQ_ueaKh0c',
    appId: '1:314805774101:ios:32d816453d6364075c6b1c',
    messagingSenderId: '314805774101',
    projectId: 'bitacoreqalpha0',
    storageBucket: 'bitacoreqalpha0.firebasestorage.app',
    iosBundleId: 'com.example.bitacoreqalpha0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8EVXO-pU8l0lG6p_3cE1IEuGZnXJdTZo',
    appId: '1:314805774101:web:9396ab1820a4e1e25c6b1c',
    messagingSenderId: '314805774101',
    projectId: 'bitacoreqalpha0',
    authDomain: 'bitacoreqalpha0.firebaseapp.com',
    storageBucket: 'bitacoreqalpha0.firebasestorage.app',
  );
}
